Module4 task1
htmlacademy-adaptive/1347475-mishka-21 pull request #8
Opened 2020-11-30 19:46 UTC by ddlein

2020-12-01 07:41 UTC, PavelNyukalo requested changes

2020-12-01 07:41 UTC, PavelNyukalo commented on source/sass/blocks/contacts.scss
> +
Насчет карты. Она вылезает за пределы контентной области и упирается в края, мне кажется она должна тянуться
![image](https://user-images.githubusercontent.com/52506235/100708448-28757d00-33ce-11eb-8b04-7fcc2ebd04b3.png)

Сейчас у нас так
![image](https://user-images.githubusercontent.com/52506235/100708489-3925f300-33ce-11eb-8321-20f8007f53ce.png)

Постарайся добиться чтобы она тянулась
![image](https://user-images.githubusercontent.com/52506235/100708514-480ca580-33ce-11eb-9f21-908bc9a01225.png)

2020-12-01 07:41 UTC, PavelNyukalo commented on source/sass/blocks/main-nav.scss
> +
Немного про это медиа-выражение. 
По сути, до планшетной версии у нас и так будет идти мобильная.
Что с этим медиа-выражением (`@media (max-width: $mobil-width-only)`), что без него, стили будут применяться, поскольку переопределяющие стили применятся только с 768рх.
Поэтому предлагаю убрать это _медиа-выражение_ (его объявление, сами стили оставь) и _переменную_ `$mobil-width-only`. Если где-то еще использовал такое медиа, там тоже убери

2020-12-01 07:41 UTC, PavelNyukalo commented on source/sass/blocks/reviews.scss
> +  }
Здесь смотри для блока задал переменную не обертки (`$tablet-wrapper`), а ширину. Поэтому для блока `.reviews` у нас применилась ширина в 768рх.
Это привело к:
1. Появился горизонтальный скролл
2. Тот же хром пытается уместить, масштабирует все блоки, шрифты и тд (возможно как раз из-за этого было такое поведение блоков на видео, которое ты отправлял)
![image](https://user-images.githubusercontent.com/52506235/100709955-cb2efb00-33d0-11eb-9e4c-d968efde7630.png)

2020-12-01 07:41 UTC, PavelNyukalo commented on source/index.html
> +          <blockquote class="reviews__item visually-hidden">
Давай другие слайды уберем с помощью `display: none`, как мы делали в нердсе

2020-12-01 19:39 UTC, ddlein commented on source/sass/blocks/about-us.scss
> +  margin-left: 20px;
ok

2020-12-01 19:56 UTC, ddlein commented on source/sass/blocks/contacts.scss
> +
ok

2020-12-02 16:36 UTC, ddlein commented on source/sass/blocks/main-nav.scss
> +
ok

2020-12-02 16:42 UTC, ddlein commented on source/sass/blocks/reviews.scss
> +  }
ok

2020-12-02 16:50 UTC, ddlein commented on source/index.html
> +          <blockquote class="reviews__item visually-hidden">
ok

2020-12-04 04:22 UTC, PavelNyukalo approved these changes

2020-12-04 04:22 UTC, merged